repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: local
    hooks:
    -   id: ruff
        name: Clean notebooks
        language: system
        entry: bash
        args: [-c, "make clean"]

-   repo: local
    hooks:
    -   id: ruff
        name: Format notebooks
        language: system
        entry: bash
        args: [-c, "make format"]
